----------------MEMBER-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO MEMBER (USER_NO, USER_ID, USER_PWD, USER_EMAIL, USER_NAME, USER_PHONE, USER_LEVEL, USER_ENROLL_DATE, USER_MODIFY_DATE, USER_STATUS) VALUES (SEQ_UNO.NEXTVAL,'admin01','admin01','admin01@gmail.com','관리일','010-1234-5678',0,to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-10-01', 'RRRR-MM-DD'),'Y');
--행 2
INSERT INTO MEMBER (USER_NO, USER_ID, USER_PWD, USER_EMAIL, USER_NAME, USER_PHONE, USER_LEVEL, USER_ENROLL_DATE, USER_MODIFY_DATE, USER_STATUS) VALUES (SEQ_UNO.NEXTVAL,'admin02','admin02','admin02@gmail.com','관리이','010-9876-5432',0,to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-10-01', 'RRRR-MM-DD'),'Y');
--행 3
INSERT INTO MEMBER (USER_NO, USER_ID, USER_PWD, USER_EMAIL, USER_NAME, USER_PHONE, USER_LEVEL, USER_ENROLL_DATE, USER_MODIFY_DATE, USER_STATUS) VALUES (SEQ_UNO.NEXTVAL,'user01','user01','user01@gmail.com','유저일','010-1111-1111',1,to_date('2023-10-05', 'RRRR-MM-DD'),to_date('2023-10-05', 'RRRR-MM-DD'),'Y');
--행 4
INSERT INTO MEMBER (USER_NO, USER_ID, USER_PWD, USER_EMAIL, USER_NAME, USER_PHONE, USER_LEVEL, USER_ENROLL_DATE, USER_MODIFY_DATE, USER_STATUS) VALUES (SEQ_UNO.NEXTVAL,'user02','user02','user02@gmail.com','유저이','010-2222-2222',1,to_date('2023-10-10', 'RRRR-MM-DD'),to_date('2023-10-10', 'RRRR-MM-DD'),'Y');
--행 5
INSERT INTO MEMBER (USER_NO, USER_ID, USER_PWD, USER_EMAIL, USER_NAME, USER_PHONE, USER_LEVEL, USER_ENROLL_DATE, USER_MODIFY_DATE, USER_STATUS) VALUES (SEQ_UNO.NEXTVAL,'user03','user03','user03@gmail.com','유저삼','010-3333-3333',1,to_date('2023-10-13', 'RRRR-MM-DD'),to_date('2023-10-13', 'RRRR-MM-DD'),'Y');
--행 6
INSERT INTO MEMBER (USER_NO, USER_ID, USER_PWD, USER_EMAIL, USER_NAME, USER_PHONE, USER_LEVEL, USER_ENROLL_DATE, USER_MODIFY_DATE, USER_STATUS) VALUES (SEQ_UNO.NEXTVAL,'user04','user04','user04@gmail.com','유저사','010-4444-4444',1,to_date('2023-10-15', 'RRRR-MM-DD'),to_date('2023-10-15', 'RRRR-MM-DD'),'Y');




----------------BOARD-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,3,'후기','게시판제목01','게시판내용01');
--행 2
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,3,'질문','게시판제목02','게시판내용02');
--행 3
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,4,'일상','게시판제목03','게시판내용03');
--행 4
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,5,'의견','게시판제목04','게시판내용04');
--행 5
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,6,'기타','게시판제목05','게시판내용05');
--행 6
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,4,'후기','게시판제목06','게시판내용06');
--행 7
INSERT INTO BOARD (BOARD_NO, BOARD_USER, BOARD_CATEGORY, BOARD_TITLE, BOARD_CONTENT) VALUES (SEQ_BNO.NEXTVAL,5,'질문','게시판제목07','게시판내용07');


----------------BOARD IMAGE-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO BOARD_IMAGE (BOARD_IMAGE_NO, BOARD_NO, BOARD_IMAGE_ORIGIN, BOARD_IMAGE_CHANGE, BOARD_IMAGE_PATH) VALUES (SEQ_BINO.NEXTVAL,1,'사진01','2023102415001848424.jpg','resources/board_upfile/');
--행 2
INSERT INTO BOARD_IMAGE (BOARD_IMAGE_NO, BOARD_NO, BOARD_IMAGE_ORIGIN, BOARD_IMAGE_CHANGE, BOARD_IMAGE_PATH) VALUES (SEQ_BINO.NEXTVAL,2,'사진02','2023102415001848425.jpg','resources/board_upfile/');
--행 3
INSERT INTO BOARD_IMAGE (BOARD_IMAGE_NO, BOARD_NO, BOARD_IMAGE_ORIGIN, BOARD_IMAGE_CHANGE, BOARD_IMAGE_PATH) VALUES (SEQ_BINO.NEXTVAL,3,'사진03','2023102415001848426.jpg','resources/board_upfile/');
--행 4
INSERT INTO BOARD_IMAGE (BOARD_IMAGE_NO, BOARD_NO, BOARD_IMAGE_ORIGIN, BOARD_IMAGE_CHANGE, BOARD_IMAGE_PATH) VALUES (SEQ_BINO.NEXTVAL,4,'사진04','2023102415001848427.jpg','resources/board_upfile/');



----------------BOARD COMMENT-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO BOARD_COMMENT (COMMENT_NO, BOARD_NO, COMMENT_USER, COMMENT_CONTENT) VALUES (SEQ_CNO.NEXTVAL,1,5,'댓글입니다1');
--행 2
INSERT INTO BOARD_COMMENT (COMMENT_NO, BOARD_NO, COMMENT_USER, COMMENT_CONTENT) VALUES (SEQ_CNO.NEXTVAL,1,4,'댓글입니다2');
--행 3
INSERT INTO BOARD_COMMENT (COMMENT_NO, BOARD_NO, COMMENT_USER, COMMENT_CONTENT) VALUES (SEQ_CNO.NEXTVAL,2,3,'댓글입니다3');
--행 4
INSERT INTO BOARD_COMMENT (COMMENT_NO, BOARD_NO, COMMENT_USER, COMMENT_CONTENT) VALUES (SEQ_CNO.NEXTVAL,3,1,'댓글입니다4');



----------------PLACE-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'가을여행지 01','계절감을 느낄 수 있는 곳입니다','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','계절','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 2
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'가을여행지 02','계절감을 느낄 수 있는 곳입니다','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','계절','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 3
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'가을여행지 03','계절감을 느낄 수 있는 곳입니다','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','계절','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 4
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'가을여행지 04','계절감을 느낄 수 있는 곳입니다','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','계절','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 5
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'가을여행지 05','계절감을 느낄 수 있는 곳입니다','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','계절','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 6
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME) VALUES (SEQ_PNO.NEXTVAL,'도심속의 핫플 01','사람 구경을 좋아한다면','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','도심','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','09:00~18:00');
--행 7
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME) VALUES (SEQ_PNO.NEXTVAL,'도심속의 핫플 02','사람 구경을 좋아한다면','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','도심','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','09:00~18:00');
--행 8
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME) VALUES (SEQ_PNO.NEXTVAL,'도심속의 핫플 03','사람 구경을 좋아한다면','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','도심','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','09:00~18:00');
--행 9
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'도심속의 핫플 04','사람 구경을 좋아한다면','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','도심','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 10
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'도심속의 핫플 05','사람 구경을 좋아한다면','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','도심','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 11
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME) VALUES (SEQ_PNO.NEXTVAL,'힐링여행지 01','휴식하기 좋은 장소','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','힐링','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','09:00~18:00');
--행 12
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME) VALUES (SEQ_PNO.NEXTVAL,'힐링여행지 02','휴식하기 좋은 장소','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','힐링','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','09:00~18:00');
--행 13
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME) VALUES (SEQ_PNO.NEXTVAL,'힐링여행지 03','휴식하기 좋은 장소','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','힐링','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','09:00~18:00');
--행 14
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'힐링여행지 04','휴식하기 좋은 장소','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','힐링','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 15
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT) VALUES (SEQ_PNO.NEXTVAL,'힐링여행지 05','휴식하기 좋은 장소','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','힐링','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037');
--행 16
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME, PLACE_START, PLACE_END) VALUES (SEQ_PNO.NEXTVAL,'대한민국 축제 01','축제를 즐기자','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','축제','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','12:00~15:00',to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-12-31', 'RRRR-MM-DD'));
--행 17
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME, PLACE_START, PLACE_END) VALUES (SEQ_PNO.NEXTVAL,'대한민국 축제 02','축제를 즐기자','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','축제','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','12:00~15:00',to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-12-31', 'RRRR-MM-DD'));
--행 18
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_TIME, PLACE_START, PLACE_END) VALUES (SEQ_PNO.NEXTVAL,'대한민국 축제 03','축제를 즐기자','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','축제','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037','12:00~15:00',to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-12-31', 'RRRR-MM-DD'));
--행 19
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_START, PLACE_END) VALUES (SEQ_PNO.NEXTVAL,'대한민국 축제 04','축제를 즐기자','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','축제','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037',to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-12-31', 'RRRR-MM-DD'));
--행 20
INSERT INTO PLACE (PLACE_NO, PLACE_TITLE, PLACE_CONTENT_POINT, PLACE_CONTENT_DETAIL, PLACE_THEMA, PLACE_ADDRESS, PLACE_HOMEPAGE, PLACE_CONTACT, PLACE_START, PLACE_END) VALUES (SEQ_PNO.NEXTVAL,'대한민국 축제 05','축제를 즐기자','상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 상세설명입니다 ','축제','서울특별시 강남구 테헤란로14길 6','https://www.iei.or.kr/main/main.kh','0507-1400-2037',to_date('2023-10-01', 'RRRR-MM-DD'),to_date('2023-12-31', 'RRRR-MM-DD'));


----------------PLACE IMAGE-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,1,'사진01','2023102415001848420.jpg','resources/images/');
--행 2
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,2,'사진02','2023102415001848421.jpg','resources/images/');
--행 3
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,3,'사진03','2023102415001848422.jpg','resources/images/');
--행 4
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,4,'사진04','2023102415001848423.jpg','resources/images/');
--행 1
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,18,'사진01','2023102415001848420.jpg','resources/images/');
--행 2
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,18,'사진02','2023102415001848421.jpg','resources/images/');
--행 3
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,18,'사진03','2023102415001848422.jpg','resources/images/');
--행 4
INSERT INTO PLACE_IMAGE (PLACE_IMAGE_NO, PLACE_NO, PLACE_IMAGE_ORIGIN, PLACE_IMAGE_CHANGE, PLACE_IMAGE_PATH) VALUES (SEQ_PINO.NEXTVAL,18,'사진04','2023102415001848423.jpg','resources/images/');



----------------PLACE LIKE-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO PLACE_LIKE (LIKE_NO, PLACE_NO, USER_NO) VALUES (SEQ_PLNO.NEXTVAL,1,3);
--행 2
INSERT INTO PLACE_LIKE (LIKE_NO, PLACE_NO, USER_NO) VALUES (SEQ_PLNO.NEXTVAL,2,3);
--행 3
INSERT INTO PLACE_LIKE (LIKE_NO, PLACE_NO, USER_NO) VALUES (SEQ_PLNO.NEXTVAL,3,3);
--행 4
INSERT INTO PLACE_LIKE (LIKE_NO, PLACE_NO, USER_NO) VALUES (SEQ_PLNO.NEXTVAL,4,4);
--행 5
INSERT INTO PLACE_LIKE (LIKE_NO, PLACE_NO, USER_NO) VALUES (SEQ_PLNO.NEXTVAL,5,5);





----------------REVIEW-----------------------
--ORA-01722: invalid number
--행 1
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,1,3,1,'최악이네요 최악이네요 최악이네요 최악이네요 최악이네요 ');
--행 2
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,1,4,2,'별로였어요 별로였어요 별로였어요 별로였어요 별로였어요');
--행 3
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,1,5,3,'그냥그래요 그냥그래요 그냥그래요 그냥그래요 그냥그래요 ');
--행 4
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,2,6,4,'좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 ');
--행 5
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,2,3,5,'최고예요 최고예요 최고예요 최고예요 최고예요 최고예요 ');
--행 6
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,2,4,1,'최악이네요 최악이네요 최악이네요 최악이네요 최악이네요 ');
--행 7
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,3,5,2,'별로였어요 별로였어요 별로였어요 별로였어요 별로였어요');
--행 8
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,4,6,3,'그냥그래요 그냥그래요 그냥그래요 그냥그래요 그냥그래요 ');
--행 9
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,5,3,4,'좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 ');
--행 10
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,6,4,5,'최고예요 최고예요 최고예요 최고예요 최고예요 최고예요 ');
--행 11
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,7,5,1,'최악이네요 최악이네요 최악이네요 최악이네요 최악이네요 ');
--행 12
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,8,6,2,'별로였어요 별로였어요 별로였어요 별로였어요 별로였어요');
--행 13
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,9,3,3,'그냥그래요 그냥그래요 그냥그래요 그냥그래요 그냥그래요 ');
--행 14
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,10,4,4,'좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 ');
--행 15
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,11,5,5,'최고예요 최고예요 최고예요 최고예요 최고예요 최고예요 ');
--행 16
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,12,6,1,'최악이네요 최악이네요 최악이네요 최악이네요 최악이네요 ');
--행 17
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,13,3,2,'별로였어요 별로였어요 별로였어요 별로였어요 별로였어요');
--행 18
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,14,4,3,'그냥그래요 그냥그래요 그냥그래요 그냥그래요 그냥그래요 ');
--행 19
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,15,5,4,'좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 ');
--행 20
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,16,6,5,'최고예요 최고예요 최고예요 최고예요 최고예요 최고예요 ');
--행 16
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,18,6,1,'최악이네요 최악이네요 최악이네요 최악이네요 최악이네요 ');
--행 17
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,18,3,2,'별로였어요 별로였어요 별로였어요 별로였어요 별로였어요');
--행 18
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,18,4,3,'그냥그래요 그냥그래요 그냥그래요 그냥그래요 그냥그래요 ');
--행 19
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,18,5,4,'좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 좋았어요 ');
--행 20
INSERT INTO REVIEW (REVIEW_NO, PLACE_NO, USER_NO, REVIEW_STAR, REVIEW_CONTENT) VALUES (SEQ_RNO.NEXTVAL,18,6,5,'최고예요 최고예요 최고예요 최고예요 최고예요 최고예요 ');



COMMIT;

